DashboardPanel:
  TemperatureWidget:
    header: null
    rows:
      - name: Bottle
        icon: bottle
        port: 80
        resource: /test-get
        component: value
        charted: true
        input:
          min: 0
          max: 15
        sub_rows:
          - name: Top
            port: 80
            resource: /test-get
            component: value
            charted: true
          - name: Bottom
            port: 80
            resource: /test-get
            component: value
            charted: true
      - name: LED array
        icon: leds
        port: 80
        resource: /test-get
        component: value
        charted: true
      - name: Boards
        icon: board
        component: value
        charted: false
        sub_rows:
          - name: Raspberry - chip
            port: 80
            resource: /test-get
            component: value
            charted: true
          - name: Board2
            port: 80
            resource: /test-get
            component: value
            charted: true
          - name: Board3
            port: 80
            resource: /test-get
            component: value
            charted: false
          - name: Board4
            port: 80
            resource: /test-get
            component: value
            charted: false
      - name: Ambient
        icon: temperature_ambient
        port: 80
        resource: /test-get
        component: value
        charted: true
    chart:
      history: 30
  LedArrayWidget:
    header:
      rows:
        - name: temperature
          type: dataField
          port: 80
          resource: /test-get
          unit: °C
          component: value
    sliders:
      - name: Channel 1
        min: 0
        max: 1
        step: 0.01
        channel: 0
      - name: Channel 2
        min: 0
        max: 1
        step: 0.01
        channel: 1
      - name: Channel 3
        min: 0
        max: 1
        step: 0.01
        channel: 2
      - name: Channel 4
        min: 0
        max: 1
        step: 0.01
        channel: 3
  CoolSpektrometerWidget:
    header: null
    rows:
      - name: UV
        frequency: 430 nm
        color: '#6F00FF'
        absolute:
          port: 80
          resource: /test-get
          component: value
          charted: true
        relative:
          port: 80
          resource: /test-get
          component: value
          charted: true
      - name: Blue
        frequency: 480 nm
        color: '#007FFF'
        absolute:
          port: 80
          resource: /test-get
          component: value
          charted: true
        relative:
          port: 80
          resource: /test-get
          component: value
          charted: true
      - name: Green
        frequency: 560 nm
        color: '#00FF00'
        absolute:
          port: 80
          resource: /test-get
          component: value
          charted: true
        relative:
          port: 80
          resource: /test-get
          component: value
          charted: true
      - name: Orange
        frequency: 630 nm
        color: '#FF7F00'
        absolute:
          port: 80
          resource: /test-get
          component: value
          charted: true
        relative:
          port: 80
          resource: /test-get
          component: value
          charted: true
      - name: Red
        frequency: 678 nm
        color: '#FF0000'
        absolute:
          port: 80
          resource: /test-get
          component: value
          charted: true
        relative:
          port: 80
          resource: /test-get
          component: value
          charted: true
      - name: IR
        frequency: 870 nm
        color: '#800000'
        absolute:
          port: 80
          resource: /test-get
          component: value
          charted: true
        relative:
          port: 80
          resource: /test-get
          component: value
          charted: true
  ControlWidget:
    header: null
    sliders:
      - name: Aerator
        min: 0
        max: 1
        step: 0.01
        unit: ' '
        decimalPlaces: 2
        port: 8089
        component: speed
        resource: /control/aerator/speed
      - name: Mixer
        min: 0
        max: 1
        step: 0.01
        unit: ' '
        decimalPlaces: 2
        port: 8089
        component: speed
        resource: /control/mixer/speed
      - name: Cuvette pump
        min: -1
        max: 1
        step: 0.05
        unit: ' '
        decimalPlaces: 2
        port: 8089
        component: speed
        resource: /control/cuvette_pump/speed
      - name: Heater
        min: -1
        max: 1
        step: 0.05
        unit: ' '
        decimalPlaces: 2
        port: 8089
        component: intesity
        resource: /control/heater/intesity
  KineticFluorometerWidget:
    header: null
DevicePanel:
  modules:
    - name: debug
      id: '0x00000000000000000'
      instance: unidentified
      data:
        - unit: ms
          resource: /debug/ping
          component: time_ms
        - unit: °C
          resource: /debug/core_temp
          component: temperature
        - unit: °C
          port: 80
          resource: /test-get
          component: value
        - unit: '%'
          port: 80
          resource: /test-get
          component: value
