#STATS
#name          = display name on the page
#source_device = "device" or "node", changes the used port 
#source        = path to the API enpoint (/temperature, /test-get, etc.)
#component     = the json attribute that holds the value
#unit          = unit (°C, rpm, lm)

[[stats]]
name="microchip"
source_device="device"
source="/temperature"
component="temperature"
unit="°C"

[[stats]]
name="random"
source_device="node"
source="/test-get"
component="value"
unit="rpm"